-- QUERY 1 - FIND AVERAGE SALARY BY DEPARTMENTS

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, AVG (S.SALARY_AMOUNT) "AVERAGE SALARY"
FROM DEPARTMENTS D
JOIN SALARY_TXN_HISTORY S ON D.MANAGER_ID = S.EMPLOYEE_ID 
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY AVG (S.SALARY_AMOUNT) DESC;

-- QUERY 2 - FIND AN EMPLOYEE WITH LAST NAME 'SINGH'

SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME
FROM   EMPLOYEES
WHERE  UPPER (LAST_NAME) = 'SINGH';

-- QUERY 3 - FIND EMPLOYEES HIRED BEFORE 1 JAN 1995

SELECT LAST_NAME, FIRST_NAME, TO_CHAR (HIRE_DATE, 'DD-MON-YYYY') "HIRE DATE"
FROM  EMPLOYEES
WHERE HIRE_DATE < TO_DATE ('01-JAN-95','DD-MON-RR');

-- QUERY 4 - FIND EMPLOYEES AND THE NUMBER OF SKILLS THEY HAVE

SELECT E.EMPLOYEE_ID, COUNT (*) "SKILL COUNT"
FROM EMPLOYEES E
LEFT JOIN SKILL_DETAILS ES
ON E.EMPLOYEE_ID = ES.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID ORDER BY E.EMPLOYEE_ID;

-- QUERY 5 - FIND WHICH BANK HOLDS THE MAXIMUM NUMBER OF ACCOUNTS

SELECT BANK_NAME, COUNT (*) "ACCOUNT COUNT"
FROM EMPLOYEE_FINANCIALS
GROUP BY BANK_NAME
ORDER BY COUNT (*) DESC;

-- QUERY 6 - QUERY TO OUTPUT A SINGLE COLUMN DISPLAYING THE FOLLOWING TEXT FOR EACH
--EMPLOYEE:
--FIRST_NAME LAST_NAME IS XX YEARS OLD AND HAS WORKED IN THE COMPANY FOR XX YEARS. 

SELECT E.FIRST_NAME||' ' ||E.LAST_NAME||' IS '|| ROUND ((SYSDATE-E.DATE_OF_BIRTH)/365)||
' YEARS OLD AND HAS WORKED IN THE COMPANY FOR '|| ROUND (MONTHS_BETWEEN(SYSDATE,E.HIRE_DATE)/12)||' YEARS. '"EMPLOYEE TENURE"
FROM EMPLOYEES E;

--- QUERY 7 – CREATING A TABLE FOR ALL EMPLOYEES WHO HAVE BEEN HIRED AFTER 1ST JAN 2000.

CREATE TABLE NEW_JOINEES AS
SELECT  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE
FROM    EMPLOYEES  
WHERE   HIRE_DATE > '01-JAN-00';

DESCRIBE NEW_JOINEES;

SELECT * FROM NEW_JOINEES;